name: SLSA Level 2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER_TEMP: /tmp/runner
      OPENSSL_PASSPHRASE: ${{ secrets.OPENSSL_PASSPHRASE }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Create Go file
        run: |
          cat > main.go <<EOF
          package main
          import "fmt"
          func main() {
              fmt.Println("hello world")
          }
          EOF
          
      - name: Initialize Go module
        run: |
          go mod init hello-go
          go mod tidy
          
      - name: Build with enhanced security
        id: build
        run: |
          go build -o hello-go main.go
          echo "hashes=$(sha256sum hello-go | base64 -w0)" >> $GITHUB_OUTPUT
          
      - name: Generate OpenSSL keys
        run: |
          openssl genpkey -algorithm RSA -out private.pem -aes256 -pass pass:${{ secrets.OPENSSL_PASSPHRASE }}
          chmod 600 private.pem
          openssl rsa -in private.pem -pubout -out public.pem -passin pass:${{ secrets.OPENSSL_PASSPHRASE }}
          
      - name: Sign artifact
        run: |
          openssl dgst -sha256 -sign private.pem -passin pass:${{ secrets.OPENSSL_PASSPHRASE }} -out hello-go.sig hello-go
          
      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator@v2.0.0
        with:
          base64-subjects: "${{ steps.build.outputs.hashes }}"
          provenance-name: "hello.intoto.jsonl"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-binary-and-provenance
          path: |
            hello-go
            hello-go.sig
            hello.intoto.jsonl
            public.pem
