name: SLSA Level 2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER_TEMP: /tmp/runner
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for provenance
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          
      - name: Initialize Go module
        run: |
          go mod init hello-go
          go mod tidy
          
      - name: Build with enhanced security
        id: build
        run: |
          # Record build environment info
          echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV
          echo "GITHUB_REF=$GITHUB_REF" >> $GITHUB_ENV
          
          # Build the binary
          go build -o hello main.go
          
      - name: Generate SLSA provenance
        uses: slsa-framework/slsa-github-generator/container@v2.1.0
        with:
          base64-subjects: "${{ steps.build.outputs.hashes }}"
          provenance-name: "hello.intoto.jsonl"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-binary-and-provenance
          path: |
            hello
            hello.intoto.jsonl
